apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: sse
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379

          # 보안 설정
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          # Redis는 메모리 기반이라 테스트에서는 간단히
          args:
            - "redis-server"
            - "--appendonly"
            - "no"

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"